### PR TITLE
Add support FreeBSD

### PR DESCRIPTION
**Pull request by nikll**

### CODE REVIEW

**Comment by t6** [comment]
:+1: Please merge this.  I'm working on a FreeBSD port for IntelliJ.  Pty4J support is needed to enable more IntelliJ features on FreeBSD.

**Comment by t6** [comment]
I created a working version (with passing tests) for FreeBSD at https://github.com/t6/pty4j/ based on @nikll's work but with a much smaller diff and only changes in the Java side of Pty4J. Also see the notes at t6/wip-ports#1.

Please tell me if there is even the slightest interest in this. If there is I will open a pull request for that version and will try to address any concerns you might have.

**Comment by traff** [comment]
Hi, I planned to merge this pull request and update pty4j in IntelliJ IDEA distribution on this week or next one. Less diff with fixes only on Java side would be grate, please create a pull request.

**Comment by traff** [comment]
Another freebsd implementation was merged in.

**Pull request closed without merging**
